name: jklTest

on: [pull_request]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
      id: go
    - name: Check out code
      uses: actions/checkout@v3
    - name: Check code format (gofmt)
      run: |
        O=$(gofmt -d -l .)
        if [ "$O" == "" ]; then echo "OK"; else echo "$O" && exit 255; fi
    - name: Create patch file & store in workspace
      run: git show --patch &> ${GITHUB_WORKSPACE}/patch
    - name: Ask ChatGPT for unit tests for new functions
      uses: zebroc/chatgpt-create-unit-tests@main
      env:
        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: chatgpt-create-unit-tests
    - name: Commit
      run: |
          echo "GIT SHOW PATCH"
          git show --patch
          echo "GIT STATUS"
          git status
          echo "GIT LOG"
          git log --pretty=oneline
          date > date.txt
          git config user.name zebroc
          git config user.email mh@zebroc.de
          echo "GIT ADD"
          git add .
          echo "GIT COMMIT"
          git commit -m "Date"
