name: jklTest

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: go fmt
      run: |
        O=$(gofmt -d -l .)
        if [ "$O" == "" ]; then echo "OK"; else echo "$O" && exit 255; fi
    - name: Patch
      run: git show --patch &> ${GITHUB_WORKSPACE}/patch
    - name: Unit tests from ChatGPT
      uses: zebroc/chatgpt-create-unit-tests@main
      env:
        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: chatgpt-create-unit-tests
    - name: Commit
      run: |
          date > date.txt
          git config user.name zebroc
          git config user.email mh@zebroc.de
          git add .
          git commit -m "Date"
          git push
