name: jklTest

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: go fmt
      run: |
        O=$(gofmt -d -l .)
        if [ "$O" == "" ]; then echo "OK"; else echo "$O" && exit 255; fi
    - name: Patch
      run: |
        git show --patch &> /tmp/patch
        echo "patch=$(cat /tmp/patch)" >> $GITHUB_OUTPUT
    - name: Unit tests from ChatGPT
      uses: zebroc/chatgpt-create-unit-tests@main
      env:
        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PATCH: ${{ steps.Patch.outputs.patch }}
      id: chatgpt-create-unit-tests
